#Makefile for "Zoo" C++ application
#Created by Carlos Vinicius 01/11/2016

zoo:
	g++ -Wall -std=c++11 -pedantic src/main.cpp src/anfibio.cpp src/animal.cpp src/animalsilvestre.cpp src/ave.cpp src/exotico.cpp src/funcionario.cpp src/mamifero.cpp src/nativo.cpp src/reptil.cpp -o bin/zoo -I include/
clean:
	rm bin/zoo